## Hentian

In [27]:
import pandas as pd

hentian = pd.read_csv('../out/rapid-bus-mrtfeeder/stops.txt')
hentian.sample(6)

       stop_id stop_code                      stop_name  stop_lat    stop_lon
915   12002390    PPJ349        SK PUTRAJAYA PRESINT 18  2.923833  101.694185
355   12002201     KJ952             WISMA UNIKEB (OPP)  2.927136  101.773124
310   12001573     KJ887                    JALAN  4/9G  2.958180  101.781850
1641  12000408     SA608  BALAIRAYA KG PAYA JARAS (OPP)  3.200278  101.553320
1281  12000564    KL1016                        PUBLIKA  3.170194  101.665338
1635  12000382     SL559            UITM SG BULOH (OPP)  3.219405  101.593238

In [26]:
hentian = pd.read_csv('../out/rapid-bus-kl/stops.txt')
hentian.sample(6)

hentian.loc[hentian['stop_name'] == 'KL141 Perumahan Polis Desa Tasik (Selatan)'.upper()]

,stop_id,stop_name,stop_desc,stop_lat,stop_lon
220,1000320,KL141 PERUMAHAN POLIS DESA TASIK (SELATAN),JLN TASIK SELATAN 20,3.066838,101.713475

In [29]:
hentian.loc[hentian['stop_code'] == 'KL1690']
hentian.loc[hentian['stop_code'] == 'KL141']

,stop_id,stop_code,stop_name,stop_lat,stop_lon
1242,12002721,KL141,PERUMAHAN PDRM DESA TASIK (PINTU 1),3.066847,101.71347

## Waktu Berhenti

In [16]:
hentian = pd.read_csv('../out/rapid-bus-mrtfeeder/stop_times.txt')
hentian.sample(5)

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,shape_dist_traveled
98223,231027020039S21,20:33:26,20:33:26,12000699,15,MRT KOTA DAMANSARA - SEKSYEN 4 & 5,7.604403
70519,231027010931S9,17:45:56,17:45:56,12001253,7,MRT TUN RAZAK EXCHANGE - TAMAN MALURI / DESA P...,4.804928
103149,231027020053S6,08:07:03,08:07:03,12001997,9,MRT JINJANG - TAMAN SRI SEGAMBUT,2.859862
119400,231027020100S18,23:46:17,23:46:17,12002381,20,MRT PUTRAJAYA SENTRAL - PRESINT 16/ALAMANDA,9.705480
136390,231027020235S10,10:15:37,10:15:37,12001091,11,MRT BUKIT DUKUNG - KG. SG. SEKAMAT,4.097032